spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=GMT
    username: root
    password: 123123
#  关闭模板引擎的缓存设置
  thymeleaf:
    cache: false
  devtools:
    livereload:
#     设置开启热部署
      enabled: true
server:
#  指定端口号
  port: 8888
mybatis:
#  指定xml文件的位置
  mapper-locations: classpath:mapper/**.xml
#  开启别名
  type-aliases-package: myboot.myblog.domain
#  开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
#  打印sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

